apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx     #这里要注意一下，这里的nginx是在部署ingress的时候就设定的名字可以使用kubectl describe daemonsets.apps -n ingress-nginx 查看
### ingress部分注释掉的都是https的annotations

#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/secure-backends: "true"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#    nginx.ingress.kubernetes.io/use-regex: "true"
  name: mysql
  namespace: devops
spec:
#  tls:
#  - hosts:
#    - k8s-dashboard.com
#    secretName: kubernetes-dashboard-certs
  rules:
  - host: mysql.com
    http:
      paths:
      - backend:
          serviceName: mysql
###    目前只暴露了8080端口用于web使用
          servicePort: 3306
        path: /


---
###  创建SERVICE链接下面的pod
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: devops
  labels:
    devops: enable
spec:
  type: ClusterIP
  ports:
### 多个port的写法
  - port: 3306
    name: connection
#  clusterIP: None
  selector:
    devops: enable




---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: devops
spec:
  selector:
    matchLabels:
      devops: enable
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        devops: enable
    spec:
      nodeSelector:
        devops: enable
      containers:
      - name: mysql
        image: mysql:5.7
        env:                        
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql 

  volumeClaimTemplates:
  - metadata:
       name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        limits:
          storage: 10Gi
        requests:
          storage: 5Gi
      storageClassName: rook-ceph-block
      volumeMode: Filesystem

